Pass regularized macro names for optional features.
Generate a config.h (currently not used).

Fix up a few shmem/pshmem interface oopsies.

pshmem off by default, I can't get the code to compile
with different compilers in all cases.  Marked as
non-stable separate configure option.  Sameer good with
this, won't break TAU integration.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -47,10 +47,10 @@ gasnet_root=$prefix
 gasnet_conduit=
 elf_header_dir=/usr/include
 elf_lib_dir=/usr/lib64
-feature_experimental=FALSE
-feature_debug=FALSE
-feature_trace=FALSE
-feature_pshmem=FALSE
+feature_experimental=DISABLED
+feature_debug=DISABLED
+feature_trace=DISABLED
+feature_pshmem=DISABLED
 # -- end defaults --
 
 libdir=
@@ -220,36 +220,36 @@ do
             elf_libs="-L$elf_lib_dir -Wl,-rpath,$elf_lib_dir"
 	    ;;
 	--enable-debug)
-	    feature_debug=TRUE
+	    feature_debug=ENABLED
 	    ;;
 	--disable-debug)
-	    feature_debug=FALSE
+	    feature_debug=DISABLED
 	    ;;
 	--enable-trace)
-	    feature_trace=TRUE
+	    feature_trace=ENABLED
 	    ;;
 	--disable-trace)
-	    feature_trace=FALSE
+	    feature_trace=DISABLED
 	    ;;
 	--enable-pshmem)
-	    feature_pshmem=TRUE
+	    feature_pshmem=ENABLED
 	    ;;
 	--disable-pshmem)
-	    feature_pshmem=FALSE
+	    feature_pshmem=DISABLED
 	    ;;
 	--enable-experimental)
-	    feature_experimental=TRUE
+	    feature_experimental=ENABLED
 	    ;;
 	--disable-experimental)
-	    feature_experimental=FALSE
+	    feature_experimental=DISABLED
 	    ;;
 	--enable-putget-nb)
 	    deprecated "$o" "--enable-experimental"
-	    feature_experimental=TRUE
+	    feature_experimental=ENABLED
 	    ;;
 	--disable-putget-nb)
 	    deprecated "$o" "--disable-experimental"
-	    feature_experimental=FALSE
+	    feature_experimental=DISABLED
 	    ;;
 	--help)
 	    show_usage
@@ -508,9 +508,9 @@ do
         -e "s%@ELF_HEADERS@%$elf_headers%g" \
         -e "s%@ELF_LIBS@%$elf_libs%g" \
         -e "s%@FEATURE_EXPERIMENTAL@%$feature_experimental%g" \
-        -e "s%@PSHMEM@%$feature_pshmem%g" \
-        -e "s%@DEBUG@%$feature_debug%g" \
-        -e "s%@TRACE@%$feature_trace%g" \
+        -e "s%@HAVE_FEATURE_PSHMEM@%$feature_pshmem%g" \
+        -e "s%@HAVE_FEATURE_DEBUG@%$feature_debug%g" \
+        -e "s%@HAVE_FEATURE_TRACE@%$feature_trace%g" \
         -e "s%@PREFIX@%$prefix%g" \
         -e "s%@BIN_DIR@%$bindir%g" \
         -e "s%@LIB_DIR@%$libdir%g" \
@@ -580,13 +580,26 @@ fi
 template="$template/tmp.XXXXXX"
 tmpcs=`mktemp $template`
 
-# clean up our temporary file on exit, or if something happens
+# save configuration options for C source code
 
+config_h="config.h"
+
+# clean up our temporary files on exit, or if something unexpected happens
+# only clean config.h if problem
+
+clean_cfg()
+{
+    rm -f $config_h
+}
 clean_tmp()
 {
     rm -f $tmpcs
 }
-trap clean_tmp 0 1 2 3 19 20
+
+trap_list="1 2 3 19 20"
+
+trap clean_tmp 0 $trap_list
+trap clean_cfg   $trap_list
 
 cat > $tmpcs <<_EOT_
 #!/bin/sh
@@ -619,6 +632,62 @@ $0 $@
 _EOT_
 cp $tmpcs $cs
 chmod +x $cs
+
+#
+# now create config.h
+#
+
+cat >> $config_h <<EOF
+/*
+ * This file was generated by the $progname script.
+ *
+ * It will be re-generated if $progname is re-run.
+ *
+ */
+
+EOF
+
+echo "#ifndef CONFIG_H" >> $config_h
+echo "#define CONFIG_H 1" >> $config_h
+echo >> $config_h
+
+echo "/* run-time debug and other sanity checks */" >> $config_h
+if [ $feature_debug = "ENABLED" ]
+then
+    echo "#define HAVE_FEATURE_DEBUG 1" >> $config_h
+else
+    echo "#undef HAVE_FEATURE_DEBUG" >> $config_h
+fi
+echo >> $config_h
+
+echo "/* run-time tracing calls */" >> $config_h
+if [ $feature_trace = "ENABLED" ]
+then
+    echo "#define HAVE_FEATURE_TRACE 1" >> $config_h
+else
+    echo "#undef HAVE_FEATURE_TRACE" >> $config_h
+fi
+echo >> $config_h
+
+echo "/* PSHMEM profiling interface */" >> $config_h
+if [ $feature_pshmem = "ENABLED" ]
+then
+    echo "#define HAVE_FEATURE_PSHMEM 1" >> $config_h
+else
+    echo "#undef HAVE_FEATURE_PSHMEM" >> $config_h
+fi
+echo >> $config_h
+
+echo "/* Experimental (non-API) routines */" >> $config_h
+if [ $feature_experimental = "ENABLED" ]
+then
+    echo "#define HAVE_FEATURE_EXPERIMENTAL 1" >> $config_h
+else
+    echo "#undef HAVE_FEATURE_EXPERIMENTAL" >> $config_h
+fi
+
+echo >> $config_h
+echo "#endif /* CONFIG_H */" >> $config_h
 
 tell ""
 tell "============================================================="
