Re-work oshrun to use conduit-specific GASNet launcher if available. This now *requires* passing NPEs to oshrun even if the underlying implementation (e.g. mpirun) could infer the number from a scheduler integration.

diff --git a/src/comms/oshrun.in b/src/comms/oshrun.in
--- a/src/comms/oshrun.in
+++ b/src/comms/oshrun.in
@@ -7,13 +7,24 @@ progname="`basename $0`"
 
 show_usage_and_exit()
 {
-  echo "Usage: $progname [conduit options] -np PEs program"
-  exit 1
+    if [ $# -gt 0 ]
+    then
+        echo "Error: $@"
+        echo ""
+    fi
+    echo "Usage: $progname [conduit options] -np PEs program [program args]"
+    echo ""
+    echo "  Where"
+    echo ""
+    echo "    -np PEs       is the number of processing elements to launch"
+    echo ""
+
+    exit 1
 }
 
 if [ $# -eq 0 ]
 then
-  show_usage_and_exit
+    show_usage_and_exit
 fi
 
 #
@@ -25,34 +36,36 @@ args=""
 
 while [ $# -gt 0 ]
 do
-  case "$1" in
-      -np)
-	  shift
-	  npes=$1
-	  ;;
-      *)
-          args="$args $1"
-	  ;;
-  esac
-  shift
+    case "$1" in
+        -np)
+	    shift
+	    npes=$1
+	    ;;
+        *)
+            args="$args $1"
+	    ;;
+    esac
+    shift
 done
 
 if [ "$npes" ]
 then
-  case "$npes" in
-    [0-9]*)
-      # good, user-supplied
-      ;;
-     *)
-      show_usage_and_exit
-      ;;
-  esac
+    case "$npes" in
+      [0-9]*)
+        # good, user-supplied
+        ;;
+       *)
+        show_usage_and_exit "NPEs is not a number"
+        ;;
+    esac
+else
+    show_usage_and_exit
 fi
 
 OPENSHMEM_GASNET_CONDUIT="@GASNET_CONDUIT@"
 export OPENSHMEM_GASNET_CONDUIT
 
-case "@GASNET_CONDUIT@" in
+case "$OPENSHMEM_GASNET_CONDUIT" in
     smp)
 	RUN_IT="env GASNET_PSHM_NODES=$npes $args"
         ;;
@@ -60,15 +73,17 @@ case "@GASNET_CONDUIT@" in
 	RUN_IT="$args"
 	;;
     mpi|ibv)
-	RUN_IT="@GASNET_LD@"
-	# set number of PEs if provided (or may come from job scheduler)
-	if [ "$npes" ]
+	# conduit-specific launcher
+	launcher="@GASNET_ROOT@/bin/gasnetrun_$OPENSHMEM_GASNET_CONDUIT"
+        if [ ! -x "$launcher" ]
         then
-          RUN_IT="$RUN_IT -np $npes"
+            show_usage_and_exit "GASNet launcher for $OPENSHMEM_GASNET_CONDUIT not found"
         fi
-        RUN_IT="$RUN_IT $args"
+	# pass number of PEs & other args
+	RUN_IT="$launcher -n $npes -- $args"
 	;;
     *)
+        # TODO: I currently have no experience of the other conduits
 	;;
 esac
 
